### ISSUE TITLE
Get Frame For Marker

### ISSUE THREAD

**Issue by Cu-Toof** [KiloKilo/WorldMatrix#3]
I have tried to get the marker's frame from `dotMatrix` to add animation. But `dotMatrix` is used to draw the image that is scale with `UIScreen.main.scale`. So I can't add view animation to the marker's position.
Could you please tell me any solution if you can?
Thank you

![simulator screen shot - iphone xs max - 2018-12-02 at 09 04 55](https://user-images.githubusercontent.com/9766953/49334805-5d993a00-f611-11e8-9acd-7eac1159bfe3.png)

**Comment by mekanics** [comment]
Hi @Cu-Toof, 

as the end output is an image, you will not be able to animate it. 

Maybe you could write a method to generate a view with the dots as layers. Then it would be possible to access each dot directly and do whatever you want with it.

**Comment by AMJ-7** [comment]
@Cu-Toof could you please share your code of scale the Green Dot
