### ISSUE TITLE
Wrong output from WorldMatrixGenerator

### ISSUE THREAD

**Issue by jalone87** [KiloKilo/WorldMatrix#4]
Swift 4.2, Xcode10, cocoapod 1.6.0.beta.2

Maybe i did understand something wrong but in generating the map with world-100 columns setting the generated output was wrong (emojis in places of the enum cases): 

THIS:

`mapMatrix += [🔵,🔵,🔵,✖️,🔵,🔶,🔶,🔶,🔶,🔶,🔶,🔶,🔶,🔶,🔶,🔹,🔶,🔶,🔶,🔶,🔶,🔶,🔶,🔶,🔶,🔵,🔶,🔵,🔵,🔵,🔶,🔶,🔵`

INSTEAD OF THE EXPECTED (like in the example project)

`mapMatrix += [.ocean,.ocean,.ocean,.ocean,.ocean,.ocean,.ocean,.ocean,.ocean,.ocean,.oce...`

My idea is that since a `description` property has been added to `WorldCharacteristic` enum, this value (the emojis) is printed to console log instead of the "string" enum cases.

I take this chance to say thank you, 
I like this pod, have been incredibly useful.

**Comment by jalone87** [comment]
Yes sure, thanks, an easy find-replace was what i did.

Anyway the emoji version was very useful to have a preview and apply immediately some fixes to the map (replace some `.unknown` and smooth some details)!

**Comment by mekanics** [comment]
@jalone87 I just pushed a new version (4.3.0) with a fix
